apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: python
    zone: prod
    version: v1
spec:
  containers:
  - name: python-app1
    image: cloudsiksha/pythonapp:v1
    ports:
    - containerPort: 8080