apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: python
    zone: prod
    version: v1
spec:
  containers:
  - name: python-app1
    image: cloudsiksha/pythonapp:v2
    ports:
    - containerPort: 80
